// Multi-document ingestion: copies every PDF from the source folder into
// public/catalogs/, runs mupdf.js structured-text extraction on each, and
// writes:
//   - lib/catalogs.ts     → small manifest (id, name, file, numPages)  [client+server]
//   - lib/chunks-data.ts  → CHUNKS_BY_DOC (id, page, bbox, text)        [server only]
// Point CATALOG_SRC at a folder of PDFs (defaults to ./source-pdfs).
// Run: CATALOG_SRC=/path/to/pdfs node scripts/ingest.mjs
import * as mupdf from "mupdf";
import {
  readFileSync,
  writeFileSync,
  readdirSync,
  mkdirSync,
  copyFileSync,
  rmSync,
} from "fs";
import { join, basename } from "path";

const SRC = process.env.CATALOG_SRC || "./source-pdfs";
const OUT_DIR = "public/catalogs";

const clamp = (v) => Math.max(0, Math.min(1, v));
const clean = (s) =>
  Array.from(s)
    .map((ch) => {
      const c = ch.codePointAt(0);
      if (c === 0xfffd || c < 0x20 || (c >= 0x7f && c <= 0x9f)) return " ";
      return ch;
    })
    .join("")
    .replace(/\s+/g, " ")
    .trim();

const slugify = (name) =>
  name
    .replace(/\.pdf$/i, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const prettyName = (name) => {
  const n = name.replace(/\.pdf$/i, "");
  if (/kompaktkatalog/i.test(n)) {
    const code = n.match(/_(PRT[A-Za-z0-9-]*)_print/i)?.[1] ?? "";
    return code
      ? `Kompaktkatalog Lagertechnik (${code})`
      : "Kompaktkatalog Lagertechnik";
  }
  return n
    .replace(/^DE_/, "")
    .replace(/Factsheet_/i, "")
    .replace(/_print$/i, "")
    .replace(/_/g, " ")
    .replace(/\s+/g, " ")
    .trim();
};

// Reset output dir.
rmSync(OUT_DIR, { recursive: true, force: true });
mkdirSync(OUT_DIR, { recursive: true });

const files = readdirSync(SRC)
  .filter((f) => f.toLowerCase().endsWith(".pdf"))
  .sort();

const catalogs = [];
const chunksByDoc = {};
const seen = new Set();

for (const file of files) {
  let slug = slugify(file);
  while (seen.has(slug)) slug += "-x";
  seen.add(slug);

  copyFileSync(join(SRC, file), join(OUT_DIR, `${slug}.pdf`));

  const buf = readFileSync(join(SRC, file));
  const doc = mupdf.Document.openDocument(buf, "application/pdf");
  const numPages = doc.countPages();
  const chunks = [];

  for (let i = 0; i < numPages; i++) {
    const page = doc.loadPage(i);
    const [x0, y0, x1, y1] = page.getBounds();
    const W = x1 - x0;
    const H = y1 - y0;
    const json = JSON.parse(
      page.toStructuredText("preserve-whitespace").asJSON(),
    );
    (json.blocks || []).forEach((block, bIdx) => {
      if (block.type !== "text" || !block.lines?.length) return;
      const text = clean(block.lines.map((l) => l.text || "").join(" "));
      if (text.length < 10) return;
      const b = block.bbox;
      chunks.push({
        id: `p${i + 1}-b${bIdx}`,
        page: i + 1,
        bbox: {
          x: clamp((b.x - x0) / W),
          y: clamp((b.y - y0) / H),
          w: clamp(b.w / W),
          h: clamp(b.h / H),
        },
        text,
      });
    });
  }

  catalogs.push({
    id: slug,
    name: prettyName(file),
    file: `catalogs/${slug}.pdf`,
    numPages,
  });
  chunksByDoc[slug] = chunks;
}

// Kompaktkatalog(s) first, then alphabetical by name.
catalogs.sort((a, b) => {
  const ak = /Kompaktkatalog/i.test(a.name) ? 0 : 1;
  const bk = /Kompaktkatalog/i.test(b.name) ? 0 : 1;
  if (ak !== bk) return ak - bk;
  if (ak === 0) return b.numPages - a.numPages; // larger Kompaktkatalog first
  return a.name.localeCompare(b.name);
});

const manifest = `// AUTO-GENERATED by scripts/ingest.mjs — do not edit by hand.
export type Catalog = {
  id: string;
  name: string;
  file: string; // public-relative path, prefix with BASE_PATH to load
  numPages: number;
};

export const CATALOGS: Catalog[] = ${JSON.stringify(catalogs, null, 0)};
export const DEFAULT_CATALOG_ID = ${JSON.stringify(catalogs[0]?.id ?? "")};
`;
writeFileSync("lib/catalogs.ts", manifest);

const chunksFile = `// AUTO-GENERATED by scripts/ingest.mjs — do not edit by hand. (server-only)
export type Chunk = {
  id: string;
  page: number;
  bbox: { x: number; y: number; w: number; h: number };
  text: string;
};

export const CHUNKS_BY_DOC: Record<string, Chunk[]> = ${JSON.stringify(chunksByDoc, null, 0)};
`;
writeFileSync("lib/chunks-data.ts", chunksFile);

const totalChunks = Object.values(chunksByDoc).reduce(
  (a, c) => a + c.length,
  0,
);
console.log(
  `docs: ${catalogs.length} | total chunks: ${totalChunks} | output: ${OUT_DIR}`,
);
